version: "3.8"

services:
  redis:
    image: redis

  backend:
    image: example-backend:v2
    container_name: be
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    ports:
      - 8080:8080

  frontend:
    image: example-frontend:v3
    container_name: fe
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5000:5000
